// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 9/26/2026, 11:49:54 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["/Users/mouzeh/Documents/constructora-nuxt/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/mouzeh/Documents/constructora-nuxt/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/mouzeh/Documents/constructora-nuxt/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/mouzeh/Documents/constructora-nuxt/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/mouzeh/Documents/constructora-nuxt/plugins/**/*.{js,ts,mjs}","/Users/mouzeh/Documents/constructora-nuxt/composables/**/*.{js,ts,mjs}","/Users/mouzeh/Documents/constructora-nuxt/utils/**/*.{js,ts,mjs}","/Users/mouzeh/Documents/constructora-nuxt/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/mouzeh/Documents/constructora-nuxt/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/mouzeh/Documents/constructora-nuxt/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/mouzeh/Documents/constructora-nuxt/app.config.{js,ts,mjs}"]}},
{}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;